---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: True
    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      instance_type: t2.micro
      security_group: default # Change the security group name here
      image: YOUR_AMI_ID #change the AMI, from which you want to launch the server
      region: us-west-2 # Change the Region
      keypair: YOUR_KEY # Change the keypair name
      count: 2 
    tasks:
    - name: Launch the new EC2 Instance
      local_action: ec2
                    group={{ security_group }}
                    instance_type={{ instance_type}}
                    image={{ image }}
                    wait=true
                    region={{ region }}
                    keypair={{ keypair }}
                    count={{count}}
      register: ec2
    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action: lineinfile
                    dest="/home/ubuntu/awsProject/hosts"
                    regexp={{ item.public_ip }}
                    insertafter="[webserver]" line={{ item.public_ip }}
      with_items: ec2.instances
      ignore_errors: true

    - name: Wait for SSH to come up
      tags: addssh
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: ec2.instances
      ignore_errors: true

    - name: Add tag to Instance(s)
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: ec2.instances
      args:
        tags:
          Name: web
